### ISSUE TITLE
Unexpected interaction with mocks

### ISSUE THREAD

**Issue by bbc2** [pallets/jinja#1139]
The bug only affects 2.11.0.  It doesn't occur on 2.10.3.

```python
from unittest import mock

import jinja2

foo = mock.Mock()
foo.return_value = "bar"
template = jinja2.Template("{{ foo() }}")
print(template.render(foo=foo))
foo.assert_called_with()
```

## Expected Behavior

```
> python foo.py
bar
```

## Actual Behavior

```
> python foo.py
bar
Traceback (most recent call last):
  File "foo.py", line 9, in <module>
    foo.assert_called_with()
  File "/usr/lib/python3.8/unittest/mock.py", line 907, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: mock()
Actual: mock(<Context {'range': <class 'range'>, 'dict': <class 'dict'>, 'lipsum': <function generate_lorem_ipsum at 0x7f8db9caa940>, 'cycler': <class 'jinja2.utils.Cycler'>, 'joiner': <class 'jinja2.utils.Joiner'>, 'namespace': <class 'jinja2.utils.Namespace'>, 'foo': <Mock id='140246696713376'>} of None>)
```

## Your Environment

* Python version: 3.8.1
* Jinja version: 2.11.0

**Comment by davidism** [comment]
The Jinja runtime determines how to call a given object based on some attributes it has. Usually, these internal attributes are set by decorators like `@jinja2.utils.contextfunction`. However, `Mock` [returns another `Mock` for any attribute access](https://docs.python.org/3/library/unittest.mock.html#deleting-attributes), and `Mock` objects are true in a boolean context.

#1108 changed the detection to use `callable`. Since `Mock` is callable, it then goes into the detection code, and since `Mock.contextfunction` is interpreted as true, Jinja thinks it should pass the context to it.

Ultimately, this is a pitfall of using too-permissive mocks generally, not something specific to Jinja. Since you expect your mock to act like a function, not an object, you should pass `spec=[]` to prevent unwanted attribute access.

```python
foo = mock.Mock(spec=[], return_value="bar")
t = Template("{{ foo() }}")
t.render(foo=foo)
foo.assert_called_with()
```

If you're doing this a lot you can use `partial` to automate it:

```python
FuncMock = partial(mock.Mock, spec=[])
mock = FuncMock(return_value="bar")
```

**Comment by rjollos** [comment]
We had a similar issue with the Trac project passing an instance of the `Href` class to a template, because our `Href` class is callable and allows arbitrary attributes that represents a path:
```python
>>> from trac.web.href import Href
>>> href = Href('/base')
>>> href.ticket(2)
'/base/ticket/2'
```

It was fixed in [r17238](https://trac.edgewall.org/changeset/17238) by disallowing `contextfunction` and associates to be used as attributes. So `href.contextfunction()` couldn't be used, but it's so unlikely someone would use it as a path fragment that it's not really a problem:
```
>>> from trac.web.href import Href
>>> href = Href('/')
>>> href.contextfunction()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    href.contextfunction()
TypeError: 'int' object is not callable
```

I was wondering about maybe changing [if getattr(__obj, 'contextfunction', 0):](https://github.com/pallets/jinja/blob/2.11.1/src/jinja2/runtime.py#L283) to `if getattr(__obj, 'contextfunction', 0) is True:`, and whether you think that might be more robust overall.

**Comment by davidism** [comment]
Changing everything to default to `False` and check `is True`, would be good for consistency. Remember that besides `context`, `evalcontext`, and `environment` -`function`, there's also -`filter` attributes as well, although they're only checked for filter functions.
