### ISSUE TITLE
Unable to refer to key names that use dot-notation

### ISSUE THREAD

**Issue by morcef** [pallets/jinja#1142]
I have generated this bug specifically using the `groupby()` filter, but this seems to be a general problem for all filters that use `_prepare_attribute_parts()`. Because of the `split(".")` in `_prepare_attribute_parts()`, one cannot use filters on dicts with key names that contain dot-notation. At least not by passing a string as attribute. https://github.com/pallets/jinja/blob/4b8d839e1ec7ac4c7e42241e9e4279826bcc3580/src/jinja2/filters.py#L125

## Expected Behavior
Input:
```input
data = [{'properties': {'first.name': 'John', 'last.name': 'Smith'}}, {'properties': {'first.name': 'Jane', 'last.name': 'Smith'}}]
```
With this input I would expect the following output:
```output
Smith
```

This expected behaviour works with itertools.groupby:
```
>>> people = []
>>> last_names = []
>>> for k, g in itertools.groupby(data, lambda x:x['properties']['last.name']):
...     people.append(list(g))
...     last_names.append(k)
... 
>>> last_names
['Smith']
>>> people
[[{'properties': {'first.name': 'John', 'last.name': 'Smith'}}, {'properties': {'first.name': 'Jane', 'last.name': 'Smith'}}]]
```

## Actual Behavior

Raises `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'last'`.

## Template Code

```jinja
{% for last_name, people in data|groupby(attribute='properties.last.name') %} 
{{ last_name }} 
{% endfor %}
```

## Full Traceback

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "~/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "~/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "~/.local/lib/python3.7/site-packages/jinja2/filters.py", line 987, in do_groupby
    for key, values in groupby(sorted(value, key=expr), expr)
  File "~/.local/lib/python3.7/site-packages/jinja2/filters.py", line 74, in attrgetter
    item = environment.getitem(item, part)
  File "~/.local/lib/python3.7/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'last'
```

## Your Environment

* Python version: 3.7.2
* Jinja version: 2.11.0

**Comment by davidism** [comment]
The second example will never work, Jinja doesn't have lambdas.

**Comment by davidism** [comment]
I don't think this is fixable. I'd recommend re-evaluating using `.` as a separator withing dict keys.

**Comment by davidism** [comment]
To fix this, we'd need to check every attribute access to see if it returned undefined, then try combining the failed part with any remaining parts, iteratively, to see if that lookup succeeds. For example, if an object looks like `obj.items["address.local"].street`, we can't do the naive thing and just look for an `address.local.street` key when `address` fails. That seems like way too much complexity to add to this.

Since this behavior has existed since at least 2011 when dotted attribute support was added (dd8afa2204149cf134e4ea30ebe51086e775218f), I don't think it's worth changing at this point.

You have a few options. You can process your data in Python, or at least pre-process it so it doesn't use dots in keys. If you're working with this operation on this type of data a lot, you'd be better served by writing a filter that's specific for your needs. For example, it could always get the first part as an attribute then remaining parts as a key.
