### ISSUE TITLE
Deprecate merged extensions

### ISSUE THREAD

**Issue by davidism** [pallets/jinja#1203]
`autoescape` and `with` have been in the standard compiler for years now. The extensions do nothing. Make them issue a deprecation warning, for removal in 3.1.

**Comment by septatrix** [comment]
I think it may be better to add the deprecation warning in a new minor 2.x release and remove them in 3.0

**Comment by FawziyahAlebiosu** [comment]
@davidism for clarification, would this warning be printed when this (https://github.com/pallets/jinja/blob/0a370316c6a4f0d034da5f90df5a671a32a8e376/src/jinja2/utils.py#L526) is called?

**Comment by davidism** [comment]
This warning would be for the extensions, that function is part of the built-in support that superseded the extensions.

The extensions are in `ext.py`, you'd want to override the `__init__` method for `WithExtension`, and `AutoEscapeExtension` to show a deprecation warning.

**Comment by FawziyahAlebiosu** [comment]
@davidism Because those two classes take in this init method here: 
https://github.com/pallets/jinja/blob/3915eb5c2a7e2e4d49ebdf0ecb167ea9c21c60b2/src/jinja2/ext.py#L73
would it be more efficient to add the warning to THAT method, or should I create an _init_ method for those two classes, and use THAT to override and show the warning?

**Comment by davidism** [comment]
Only those two extensions are deprecated, not all extensions, so you shouldn't add the deprecation to the base class.

**Comment by FawziyahAlebiosu** [comment]
that makes sense to me. Is it okay to begin working on this?

**Comment by davidism** [comment]
Sure!
