### ISSUE TITLE
docs: copy/pasting the first example, it prints the template twice 

### ISSUE THREAD

**Issue by mhansen** [pallets/jinja#1239]
Hi! First up, thanks for Jinja2, it's made a big difference to the security of the websites I run having easy autoescaping in Python.

Forked off as a separate issue from https://github.com/pallets/jinja/issues/1211#issuecomment-633326894. I understand why this happens (it's because `PackageLoader` re-loads `test.py` which re-runs all the code in `test.py`), but it took me over an hour of head-scratching to figure it out, and I'm probably not the only one who was caught out by the example given not working out of the box.

I know you mention "This loader only requires that yourapp is importable" -- I think it would really help users along their first jinja2 integration to also provide an importable example.

## To Reproduce

Copy/paste the example code from https://jinja.palletsprojects.com/en/master/api/#basics

`test.py`:
```
from jinja2 import Environment, PackageLoader, select_autoescape
env = Environment(
    loader=PackageLoader('test', 'templates'),
    autoescape=select_autoescape(['html', 'xml'])
)
template = env.get_template('mytemplate.html')
print(template.render(the='variables', go='here'))
```

`templates/mytemplate.html`:
```
<!doctype html>
<html>the {{the}} go {{go}}
</html>
```

## Expected Behavior

Should evaluate and print the template once:

```
$ python3 test.py
<!doctype html>
<html>the variables go here
</html>
```

## Actual Behavior

Prints the templates twice:

```
$ python3 test.py
<!doctype html>
<html>the variables go here
</html>
<!doctype html>
<html>the variables go here
</html>
```

## Your Environment
* Python version: Python 3.7.7
* Jinja version: 2.10

**Comment by mhansen** [comment]
Spitballing here. It's high-overhead and talks about `__main__` which is a fairly weird python construct for newbies, but this should work:

```
from jinja2 import Environment, PackageLoader, select_autoescape

def main():
  env = Environment(
      loader=PackageLoader('test', 'templates'),
      autoescape=select_autoescape(['html', 'xml'])
  )
  template = env.get_template('mytemplate.html')
  print(template.render(the='variables', go='here'))

if __name__ == '__main__':
  main()
```

This works:

```
> python3 test.py
<!doctype html>
<html>the variables go here
</html>
```

**Comment by davidism** [comment]
I understand that this looks weird, but I don't think this is in scope for these docs. The docs are meant to demonstrate the basic usage of the loader system, not to be used in isolation. In a real application, this won't happen. I don't want to add more complexity to this example.

**Comment by mhansen** [comment]
I'm keen to have simple examples too.

As a possibly simpler alternative to the __main__ thing, how about putting
the template loader into a different file (templates.py) and importing &
printing in main.py?

We should certainly try to simplify examples as far as we can, but I would
argue that examples simplified to the point that they don't work are
counterproductive. I'd argue that if we're giving an example first thing in
the API docs, the example should work, and not print twice?

I assure you this does come up in real applications - it happened to me in
a real situation while writing a doc generator for Graphviz (
https://gitlab.com/graphviz/graphviz/-/blob/master/doc/infosrc/mkattrs.py#L143
).

Looks like people have had trouble with this a few times over the years:
- https://github.com/pallets/jinja/issues/391
- https://github.com/pallets/jinja/issues/255
-
https://www.reddit.com/r/learnpython/comments/r1412/help_with_simple_jinja2_example/
- 9 upvotes on this stackoverflow question of someone trying to copy/paste
the example: https://stackoverflow.com/q/14276829/171898

**Comment by WolfgangFahl** [comment]
I wonder why this is closed if    

-  https://stackoverflow.com/questions/51234494/import-module-from-above-folder-does-not-work-with-ci-server
-  https://stackoverflow.com/questions/10095037/why-use-sys-path-appendpath-instead-of-sys-path-insert1-path
-  https://stackoverflow.com/questions/38617900/need-to-package-jinja2-template-for-python

are discussing this at lenght. Today I create a python test case 
```
def createPackage(self,packageFolder,templateFolder,moduleName,moduleCode,templateCode):
        moduleFolder="%s/%s" % (packageFolder,moduleName)
        os.makedirs(moduleFolder,exist_ok=True)
        absTemplateFolder="%s/%s" % (moduleFolder,templateFolder)
        os.makedirs(absTemplateFolder,exist_ok=True)
        modulePath="%s/__init__.py" % moduleFolder 
        with open(modulePath,"w") as moduleFile:
            moduleFile.write(moduleCode)
        templatePath="%s/test.html" % (absTemplateFolder)
        with open(templatePath,"w") as templateFile:
            templateFile.write(templateCode)
        
    def testIssue14Templates(self):
        '''
        test template handling
        '''
        packageFolder='%s/www.wikicms' % tempfile.gettempdir()
        templateFolder='templates'
        moduleName='bitplan_webfrontend'
        moduleCode="""
def test():
    pass
        """
        templateCode="""
{{ msg }}        
"""
        self.createPackage(packageFolder, templateFolder, moduleName, moduleCode, templateCode)
        frontend=self.server.enableFrontend('www',debug=True)
        #self.assertEqual(templateFolder,frontend.site.templateFolder)
        self.assertEqual(moduleName,frontend.site.packageName)       
        html,error=frontend.renderTemplate("test.html",{"msg":"Hello world!"})
        self.assertIsNone(error)
        self.assertTrue("Hello world!" in html)
        
```

with the weird behavior that it works in my mac os environment with a macports python 3.8.6 as well as on my Ubuntu 20.04 LTS server with a python 3.8 in a jenkins environment. In the CI environments at github and travis the code chokes with the error 

"no module named ..."

No matter what i try - see a list of builds at https://github.com/BITPlan/pyWikiCMS/actions

The question https://stackoverflow.com/questions/38642557/how-to-load-jinja-template-directly-from-filesystem  has some 79 k hits and the comment:

_Sort of ridiculous you can't load a template from a file in one line e.g. jinja2.load_template('template.html')_ 

has 104 upvotes.
For me this sounds like a big need to have better template loading handling that is less complicated. My assumption would be if a i load a template from a directory that it would be possible to hint that everything else in that directory should be considered a valid "context" for the template so that it's not necessary to fiddle with sys.path or any other python internals in a way that is incompatible with the design of Jinja2. 

I think the complexity should be completly hidden as proper information hiding would suggest. So please reopen this dicussion of let me know whether i should file a separte bug report/feature request.
