### ISSUE TITLE
Consider adding |items filter

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/jinja#1561]
Currently the method of choice to iterate over dictionaries is `foo.items()` or `foo|dictsort`. The former requires that the item provided does in fact have an `.items` method which is sensible to assume in general. The `dictsort` filter does the same but also sorts.

In MiniJinja the issue came up that there is no `.items` implemented there as I did not intend on implementing this method there. In MiniJinja I would prefer to have a `|pairs` filter. The reason for this is twofold: on the one hand is `.items()` a Python-ism that shines through, on the other hand does it create this challenge that the same syntax does different things (method access vs item lookup). In Jinja2 this problem has been addressed by changing the order of priority between attribute and item access which requires users to use `foo["items"]` if they do not want to refer to the method. This has been a source of bugs in the past and as a result I was considering not making the same mistake again.

At the same time I do not really wish to create some new patterns in MiniJinja if they do not exist in Jinja2 itself.

My proposal is now to either implement `.items()` in MiniJinja regardless or to implement `|pairs` / `|items` in both. It would effectively just call `.items()` on the passed value.

The main benefit would be that it's easier to write templates in a common subset of Jinja2 that works also in languages that are not backed by Python objects.

Refs https://github.com/mitsuhiko/minijinja/issues/32

**Comment by RonnyPfannschmidt** [comment]
i love the idea of ensuring a good subset of jinja 2 is possibly available across a number of languages

**Comment by davidism** [comment]
What's the cutoff for turning Python built-in type methods into filters? `items()` makes sense, but I'm sure there are other commonly used methods. There's only one filter namespace, so it will get more difficult to find the correct method or remember the slightly different filter name for it the more we add.

I was going to suggest that `for key in data: data[key]` is a more portable form (although I don't know if that's true, I think Python is somewhat unique in iterating keys only). But it sounds like you think that would cause issues, could you expand on that?

If we add `|pairs`, which is a more general name than `|items`, does it still only work for dicts? What about Werkzeug's `MultiDict`: either it does `data.items()` and only returns the first value, or it does `dict.items(value)` and return lists of values. What about a list of tuples, or other iterables?

I'm aware of a few other non-Python implementations of the Jinja2 language:

* https://github.com/jinja2cpp/Jinja2Cpp @rmorozov
* https://github.com/HubSpot/jinjava @jasmith-hs

I'm not sure if they've considered the issue of writing templates without relying on language-specific types and methods, but I'd be interested in getting the perspectives of other implementations.

Somewhat related to this issue, but at a higher level, I'm interested in more formally specifying the grammar and behavior of the Jinja2 compiler and runtime. See #1194.

**Comment by davidism** [comment]
Regarding my first point about a cutoff, is there a strong use case for writing templates that will be rendered by different primary languages? It seems like it would be very easy to write something that is not portable. You might refer to some Python built-in type or method that doesn't translate. Or even syntax itself, such as Python keyword arguments not existing in Java.

I guess this is your alternative option of implementing `.items()` in minijinja, but perhaps there is some more generic way we can solve this, such as identifying a set of types and methods that should always be available. For example, if we say that Python dict and methods should be available, minijinja could offer a `PyDict` wrapper class that users should use if they want to write portable templates.

**Comment by ThiefMaster** [comment]
> I was going to suggest that `for key in data: data[key]` is a more portable form 

Please not; it's not only very ugly (needs `{% set value = data[key] %` or quickly becomes a mess in larger loops} but also makes it harder to tell people who aren't that familiar with Python yet that this is an anti-pattern in Python...

**Comment by davidism** [comment]
I think if we're talking portability, we have to consider not being as idimatic in any one language, but point taken. That''s basically the easiest resolution (no code change required), not necessarily the one I think we should end up with.

**Comment by mitsuhiko** [comment]
> What's the cutoff for turning Python built-in type methods into filters?

I don't think there is a clear cutoff. Jinja2 already has `|title`, `|lower` and `|upper` as example which one could argue area also just Python methods. What makes `.items()` special is that it both clashes with the subscription syntax and that it's incredible common in iteration.

> If we add `|pairs`, which is a more general name than `|items`, does it still only work for dicts?

My assumption would be that it does `.items()` or equivalent and it might fall back to `for key in x: value = x[key]` if for whatever reason there is no `.items()` on the dict.

> Somewhat related to this issue, but at a higher level, I'm interested in more formally specifying the grammar and behavior of the Jinja2 compiler and runtime. See #1194.

Generally I think only a subset of Jinja2 should be defined. I'm starting to throw out some things purposefully in MiniJinja because they make the implementation incredibly complex and I'm assuming some others ran into the same issue before me.

**Comment by davidism** [comment]
> Generally I think only a subset of Jinja2 should be defined. I'm starting to throw out some things purposefully in MiniJinja because they make the implementation incredibly complex and I'm assuming some others ran into the same issue before me.

I agree, there's a distinction between "here's the portable behavior of Jinja2" and "here's the behavior of Python-Jinja2." If we can specify what's reasonable to implement portably, it makes my life as a maintainer easier too, as I can have a better sense of what feature requests to focus on or reject. Since you're in the middle of a new implementation (and you're the original author), you probably have some good insight into what a spec might look like, if you have the time to comment there.

**Comment by davidism** [comment]
A problem I have in any of these discussions is that I don't know the original reasons behind the design decisions. The `|title`, etc. filters are *literally* equivalent to `value.title()`, they don't even try to convert the value to a string first. Why were these added in the first place as opposed to writing `value.title()` directly? I'm not convinced we should use their presence to justify more methods-as-filters, especially since there is only one filter namespace.

Let's ignore `items()` and pretend that all Python built-in types and methods are equally common in templates. In this case, the only way I can think of to write compatible templates across language implementations is to canonicalize the Python types and (a subset of) methods (since that implementation came first), and require other implementations to provide wrappers around their native data types. Users who want to write portable templates would need to wrap their data in an appropriate type and call its methods, users who don't care about portability can pass data directly and use whatever methods/idioms the implementing language provides.

**Comment by mitsuhiko** [comment]
> Let's ignore items() and pretend that all Python built-in types and methods are equally common in templates.

That argument just drives it into an absurd extreme position. First of all we already know that not all methods are equally common, secondly the argument is exclusively about items here.

As of why things exist that might not need to exist: don’t forget there was a jinja 0.9 and jinja 1 which predate the expressiveness of modern Jinja by a long time. The original reasons why things are as they are should not justify much about what Jinja should do nowadays.

**Comment by davidism** [comment]
Just to be clear, I'm fine with adding a filter. I'd prefer `|dict_items` to make it clear what the behavior is and to avoid adding a generic name to the namespace. If someone wants to get a PR in, the 3.1 release is happening very soon. The rest of this is just me thinking about the general idea of portability, specifications, and how to make decisions about future filter requests.

> predate the expressiveness of modern Jinja

I never used or maintained the Jinja0 or Jinja1 languages, so I don't know what was added because of limitations versus some other consideration. I'm not even sure where the source and docs are to try to look that up, it wasn't on pocoo by the time I got involved.

> The original reasons why things are as they are should not justify much about what Jinja should do nowadays.

I agree, that's why the presence of `|title` and other string methods shouldn't be a justification in the future if other filters are requested.

**Comment by davidism** [comment]
I'm find with the `|pairs` name if we want to make it more generic, such as trying `dict.items(data)`, then `data.items()`, then `for k in data: data[k]`. Just make sure to clearly document what it does.

**Comment by RonnyPfannschmidt** [comment]
Would it make sense to enumerates sequences as well?

If the basic idea is to iterate across lookup keys and values

It would naturally map to enumerate/mapping items in python

And more generically perhaps vars/own-keys in other languages

Is there any serialisation concept generally accepted that could be used to make a universal base idea for the name?

**Comment by davidism** [comment]
A sequence of `(key, value)` tuples is directly iterable, it doesn't require special processing.

**Comment by RonnyPfannschmidt** [comment]
i believe the key question is how does the generalized concept for getting there from sequences, mappings and possibly objects/"serializable" objects look like

**Comment by mitsuhiko** [comment]
I think the concept of making sequences into enumerated pairs does make sense generally speaking. It does not come up often in Jinja because of ``{{ loop.index0 }}`` though.

**Comment by mitsuhiko** [comment]
A quick strawpoll on Twitter suggested that `pairs` is an unpopular name. Python people mostly responded in favor of `items`, JavaScript people in favor of `entries`. I have a small tendency right now to name it `items` to make it feel at home in the original ecosystem.

**Comment by mitsuhiko** [comment]
I would propose to go ahead with naming it `|items` only and go with the behavior outlined in the PR. In two releases or so I would then propose to change the documentation patterns to use `|items` instead of `.items()`. Any objections?
