### ISSUE TITLE
ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by mailtosumitrai** [pallets/jinja#1585]
# Description
Markup has release a new version and now Jinja throws an error.

```
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dbt/utils.py", line 9, in <module>
    import jinja2
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/environment.py", line [25](https://github.com/cloudfactory/edw-dbt/runs/5243038097?check_suite_focus=true#step:7:25), in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/markupsafe/__init__.py)
Error: Process completed with exit code 1.
```

# Bug Replication

Install Jinja with MarkupSafe 2.1.0

# Expected behavior

No errors when importing jinja.

# Environment

- Python version: 3.8.12
- Jinja version: 2.11.3
- MarkupSafe: 2.1.0

**Comment by davidism** [comment]
Jinja 2.x has not been supported for some time. Upgrade Jinja, and use something like pip-tools to pin your dependencies.

**Comment by lasote** [comment]
> Jinja 2.x has not been supported for some time. Upgrade Jinja, and use something like pip-tools to pin your dependencies.

IMHO that is not reasonable at all. Many projects are still using Jinja 2 and the fix is easy.

**Comment by ThiefMaster** [comment]
You're supposed to ping your dependencies anyway, and if Jinja made a 2.11.x update you'd have to update your pins anyway (you *did* pin Jinja, right? Otherwise you'd get 3.x!), so why not just add a pin for markupsafe instead?

**Comment by lasote** [comment]
But in this case, it's an ImportError and it is necessary, and if you consider jinja2 deprecated, creating a patch shouldn't be annoying for anyone.

> . IMHO it should be installed in an isolated venv where YOU control all the versions

Yes, we have that discussion often with our users but with Conan you write Python recipes and the user can plugin extension written in Python, so in that sense is a library and the could have other requirements.

**Comment by aditya-kar** [comment]
Now that we know that it is breaking all other libraries that are dependent on Jinja 2.x, including Flask 1.1.4, could we please pin the max version of MarkupSafe?

**Comment by gzamboni** [comment]
> Jinja 2.x has not been supported for some time. Upgrade Jinja, and use something like pip-tools to pin your dependencies.

This is a little bit awkward... Flask still uses Jinja2... 😯

**Comment by ThiefMaster** [comment]
Flask uses Jinja2 v3.x. Not v2.x

**Comment by davidism** [comment]
Please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like pip-tools to pin your dependencies and control when you get updates.

**Comment by aditya-kar** [comment]
> Flask uses Jinja2 v3.x. Not v2.x

Everything below Flask v2.x uses Jinja2 v2.x. Flask v1.x is still in wide use. A snippet below from Flask's setup.py.

```
    install_requires=[
        "Werkzeug >= 0.15, < 2.0",
        "Jinja2 >= 2.10.1, < 3.0",
        "itsdangerous >= 0.24, < 2.0",
        "click >= 5.1, < 8.0",
    ],
```

**Comment by lasote** [comment]
@jeremy-coulon https://github.com/conan-io/conan/issues/10611

**Comment by chongkong** [comment]
Hi, since the `jinja2==2.11.3` has dependency `markupsafe>=0.23` without upper constraints, this led to **break all library versions** that transitively depends on `jinja2<3` (notably, `flask<2`). That is a wrong constraints, and the most simplest fix would be releasing a patch release `jinja2==2.11.4` with `markupsafe>=0.23,<2.1.0` constraints.

Application developers can add their constraints.txt file to add an upper cap, but library developers have no way to provide extra constraint for non-direct dependency except for marking it as a direct dependency, which would add up more chaos in python library dependencies. This is not a good way to go.

For example, I'm maintaining `tfx` library which has extra dependency on `airflow`, which has a dependency `flask<2`. This breaks our library. Options that I can choose of:

1. Ask `jinja2` library to release a 2.11.4 patch with `markupsafe<2.1` constraints.
2. Ask `flask` library to release a 1.1.5 patch with adding `markupsafe<2.1` dependency
3. Ask `airflow` library to upgrade their flask version to `flask>=2`.

Option 3 is probably what jinja2 maintainer is thinking about, but IMHO there will be so many other libraries which depends on `flask<2`, and the holistic effort for the migrations to flask v2 (I don't know whether there's a breaking changes introducedd) would be HUGE.
Option 2 is the worst idea because it is adding a wrong dependency for a workaround.

I think Option 1 is the easiest and the simplest solution to the current situation. I know it is hard to keep releasing a older version of the library (e.g. tensorflow maintains their 1.x version), but that would greatly help the python community.

I sincerely beg `jinja2` team to do a patch release. 🙇

**Comment by mattslezak-shell** [comment]
I don't understand the big deal, the fix with jinga2 is simple:

`runtime.py` and `filters.py`:

Change: `from markupsafe import soft_unicode`
To: `from markupsafe import soft_str as soft_unicode`

Although I get confused on this site where jinja2 is actually located, or if it's a dead package.  What brought me here is Spyder Python IDE uses this package, I traced the errors, I fixed them with the above very easily.

**Comment by ThiefMaster** [comment]
Jinja is not dead. But old versions are unsupported, and people should pin all their dependencies if they rely on older versions (which is perfectly fine, but not without pinning deps).

**Comment by zachliu** [comment]
@chongkong the new airflow 2.2.4 doesn't have such issue, it has 
```
Flask==1.1.2
Jinja2==3.0.3
MarkupSafe==2.0.1
```
in its [constraints](https://raw.githubusercontent.com/apache/airflow/constraints-2.2.4/constraints-3.8.txt)
well, at least for Python 3.8 :grinning:
