### ISSUE TITLE
Recent upgrade of MarkupSafe has broken Jinaj2 import

### ISSUE THREAD

**Issue by charlie-ht** [pallets/jinja#1592]
Markupsafe2 is depended on like this "MarkupSafe>=2.0", but the latest release 2.1.0 is incompatible,

https://github.com/pallets/jinja/blob/1c4066a4fad5aaeb2ac55809d1d38477cd23a0f6/setup.py#L6

Our CI suddenly started complaining when importing jinja2,

```
Traceback:
...
src/valve_gfx_ci/executor/server/boots.py:3: in <module>
    import jinja2
.tox/py39-coverage/lib/python3.9/site-packages/jinja2/__init__.py:12: in <module>
    from .environment import Environment
.tox/py39-coverage/lib/python3.9/site-packages/jinja2/environment.py:25: in <module>
    from .defaults import BLOCK_END_STRING
.tox/py39-coverage/lib/python3.9/site-packages/jinja2/defaults.py:3: in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
.tox/py39-coverage/lib/python3.9/site-packages/jinja2/filters.py:13: in <module>
    from markupsafe import soft_unicode
E   ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/builds/mupuf/valve-infra/executor/server/.tox/py39-coverage/lib/python3.9/site-packages/markupsafe/__init__.py)
```

- Python version: 3.9
- Jinja version: 2.11.3

Solved by downgrading MarkupSage in our build,

    MarkupSafe===2.0.1  # 2.1 broke Jinja2 

I think the fix for jinja2 is to use `MarkupSafe~=2.0`

**Comment by davidism** [comment]
You are using an unsupported version of the project, please update to the latest version. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
