### ISSUE TITLE
new in 3.1.0: ImportError: cannot import name 'Markup' from 'jinja2' 

### ISSUE THREAD

**Issue by willjhenry** [pallets/jinja#1632]
Traceback (most recent call last):
  File "/Users/williamhenry/Documents/Elate_App/app_envs/operations_dashboard/bin/flask", line 5, in <module>
    from flask.cli import main
  File "/Users/williamhenry/Documents/Elate_App/app_envs/operations_dashboard/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/Users/williamhenry/Documents/Elate_App/app_envs/operations_dashboard/lib/python3.7/site-packages/jinja2/__init__.py)

Environment:

- Python version: Python 3.7.4
- Jinja version: 3.1.0
- Flask version: 1.0.2

**Comment by davidism** [comment]
That was previously deprecated, then removed, called out both times in the changelog. Use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by davidism** [comment]
You are using an unsupported version of Flask, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by willjhenry** [comment]
Got it, thank you.
