### ISSUE TITLE
jinja fails to render if template is a FIFO

### ISSUE THREAD

**Issue by hgl** [pallets/jinja#1641]
I'm using [jinja2-cli](https://pypi.org/project/jinja2-cli/) to render a template that is actually a FIFO

```shell
fifo=$(mktemp -u)
mkfifo "$fifo"
gen_tpl >"$fifo" &
jinja2 "$fifo" -
```
It fails with

```
jinja2.exceptions.TemplateNotFound: <filename>
```
I believe the cause is this line of code: 
https://github.com/pallets/jinja/blob/6f79daafe868b8ef20baecdcb45d12299529ed2e/src/jinja2/utils.py#L159

Which precludes FIFOs.

It'd be great if FIFO could be supported. In POSIX, if you want to directly redirect stdout to a command that only accepts a "file", FIFO is probably the only way to do that (writing to a real file works too, but it's not direct).

Environment:

- Python version:
- Jinja version:

**Comment by davidism** [comment]
I think this use case is outside the intended use of `FileSystemLoader`, which jinja2-cli uses. The loader is intended to load a group of regular files under a directory.

If you think the issue is that `os.path.isfile` doesn't consider a FIFO a file, then you should report a bug to Python.

If you think the issue is that jinja2-cli should allow loading any type of file, then you could report a bug that it should use a custom loader that works with any POSIX file object.

**Comment by hgl** [comment]
Thanks for the quick reply David.

I see your point, and I have to apologize that I didn’t make it clear what I think the issue was.

Since a FIFO lives in the file system (i.e., has a path), and is readable like a regular file, I think it could perfectly be treated as a template file.

Currently, the file check logic is that jinja doesn’t care if the item has a path and is readable, as long as it’s not a regular file, it’s rejected. I wonder if it could relent a bit? Like just open it and handle exceptions for example or an check function that doesn’t insist regular files? For all jinja can care, shouldn’t a path and readable content be good enough as a template source?

Just my 2 cents.
