### ISSUE TITLE
Error importing soft_unicode from Markupsafe after using jinja2/filters.py

### ISSUE THREAD

**Issue by sarahLechtser** [pallets/jinja#1804]
Problem description:
I encountered the following error when running from rpy2.objects.vectors import Vector:
cannot import name 'soft_unicode' from 'markupsafe'
which uses jinja2/filters.py.
This is because Markupsafe has a new version that removed the soft_unicode module, causing a compatibility issue with Jinja.

Steps to reproduce:
Install rpy2 and Jinja.
Run from rpy2.objects.vectors import Vector.

**Comment by davidism** [comment]
You are using an unsupported version of Jinja, please update to the latest version (3.1.2) if possible.

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of those types of changes early.
