### ISSUE TITLE
Add pathlib.Path support to FileSystemLoader

### ISSUE THREAD

**Issue by rosejn** [pallets/jinja#1879]
The FileSystemLoader expects a string that it can call split() on, so it breaks when passed a PosixPath object resulting from a path.Path construction (e.g. glob).  I think just calling str(path) on the loader template path should do the trick.  Thanks for Jinja!

**Comment by davidism** [comment]
You've confused file system paths with Jinja template names. In the case of `FileSystemLoader`, the names match the paths on the filesystem (with slashes normalized to `/`). But Jinja template names are not paths, because there are other loaders besides `FileSystemLoader` and a template name can be any string value.
