### ISSUE TITLE
add filter `tojson`

### ISSUE THREAD

**Issue by schettino72** [pallets/jinja#458]
It would be very useful to add builtin filter to convert values to json.

Actually there is already an implementation in flask http://flask.pocoo.org/docs/0.10/templating/#standard-filters

If you guys agree I could work on a pull-request for that.

**Comment by tima** [comment]
Ansible also implements a to_json and a to_nice_json (pretty JSON) filter to Jinja2. See around line 64 here: https://github.com/ansible/ansible/blob/e07dde1a3ce88f4ba21f779f4c2cb2d78397f34b/lib/ansible/plugins/filter/core.py#L64

**Comment by snoack** [comment]
My pull request adds a filter called `json` which effectively just calls `json.dumps()`. I think it make sense to have this in upstream jinja2, as every other project using jinja2 I've seen adds a filter like this.

I went for `json`rather than `tojson`, to match the naming convention of other filters like `list` and `int`.

Additional, keyword arguments are passed through to `json.dumps()`. However, I made `ensure_ascii` default to `False`. So pretty printing is as simple as `{{ obj|json(indent=4) }}`

**Comment by thatarchguy** [comment]
+1 pretty print

**Comment by kiddick** [comment]
Bump
Why this is still open?

**Comment by moigagoo** [comment]
What's missing to merge the PR?

**Comment by Bedotech** [comment]
+1

**Comment by jeffwidman** [comment]
@snoack has merge rights, not sure if he's holding off for some reason...
