### ISSUE TITLE
urlencode doesn't escape slashes

### ISSUE THREAD

**Issue by chuwy** [pallets/jinja#515]
This was raised in #444, but [this code](https://github.com/mitsuhiko/jinja2/commit/46acbf02ed9ab58c7a92553c95790e75bdc3c930#diff-8f76b794bd641afb7bd92eba51f332f3R298) always evaluates to `b'/'` on Python 3.4.1, so slashes still not escaped.

**Comment by chuwy** [comment]
Just a heads up @mitsuhiko 
I have no idea why, but  `do_urlencode` still doesn't escape slashes, while `unicode_urlencode` works as expected.
```
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> jinja2.utils.unicode_urlencode("http://url.by", for_qs=True)
'http%3A%2F%2Furl.by'
>>> jinja2.filters.do_urlencode("http://url.by")
'http%3A//url.by'
>>> jinja2.__version__
'2.9.dev'
```

**Comment by mitsuhiko** [comment]
Because the `urlencode` filter does not escape slashes. Is there a specific reason why it has to?

**Comment by chuwy** [comment]
I believe this is standard behaviour for function intended for encoding urls. Tools like http://meyerweb.com/eric/tools/dencoder/ behave this way. Also I have at least one tool inside our company which expects URLs being passed inside GET requests with escaped slashes.
Also, I don't understand why `unicode_urlencode` [called](https://github.com/mitsuhiko/jinja2/commit/46acbf02ed9ab58c7a92553c95790e75bdc3c930#diff-33dcdc15f917259c644200be7d924eb0R97) inside `do_urlencode` with `for_qs=True`.
May be I understand something wrong.

**Comment by mitsuhiko** [comment]
Slashes are reserved characters in the path component and the more common behavior is to encode everything but slashes there when forcing things to url encoded behavior.  The alternative (to encode slashes to `%2f`) does not even make sense as most servers outright reject those requests due to security problems as backend servers typically cannot distinguish `%2f` and `/` in the path component as they operate on decoded octets.

So the only part where a slash actually makes sense encoding is in query strings and this is where the dict based encoder that `urlencode` has works like that.  However even there a slash does not have to be encoded, so there is no reason to force it to be encoded.

The `urlencode` function should use for most people by default that's why it does not encode a slash.  If you have custom requirements then you can override the function in your filter registration.

**Comment by chuwy** [comment]
Ok. Thank you Armin.

**Comment by linwukang** [comment]
Hi, I got a same trouble with reject slash, here is the code:

>>> jinja2.Template("{{ disks|reject('sameas', '/')|list }}").render(disks=["/", "/mnt/disk0", "/mnt/disk1"])
u"['/', '/mnt/disk0', '/mnt/disk1']"

I want to reject root disk, but it not work anymore, how to solved it?

**Comment by ThiefMaster** [comment]
```
>>> import jinja2
>>> jinja2.Template("{{ disks|reject('sameas', '/')|list }}").render(disks=["/", "/mnt/disk0", "/mnt/disk1"])
u"['/mnt/disk0', '/mnt/disk1']"
>>> jinja2.__version__
Out[3]: '2.8'
```

Works for me.

**Comment by linwukang** [comment]
Still not work for me, @ThiefMaster, would the a python issue? what's the version of python you used.

        Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
        Type "help", "copyright", "credits" or "license" for more information.
        >>> import jinja2
        >>> jinja2.Template("{{ disks|reject('sameas', '/')|list }}").render(disks=["/", "/mnt/disk0", "/mnt/disk1"])
        u"['/', '/mnt/disk0', '/mnt/disk1']"
        >>> jinja2.__version__
        '2.8'

**Comment by ThiefMaster** [comment]
Oh.. `sameas` uses `is`. You want `equalto` which uses `==`.

**Comment by linwukang** [comment]
Yes it works, I'm not family with Jinja2. Thanks, @ThiefMaster

**Comment by MartinNowak** [comment]
> So the only part where a slash actually makes sense encoding is in query strings and this is where the dict based encoder that urlencode has works like that. However even there a slash does not have to be encoded, so there is no reason to force it to be encoded.

No, for example you need to encode `/` in usernames and passwords as well.
It's the reason why JS has [encodeURI](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) __and__  [encodeURIComponent](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent).

**Comment by mitsuhiko** [comment]
That's fair enough but in practice it's not necessary there either and included credentials are deprecated anyways. Since those are unlikely to be produced within templates it's an edge case that is not really worth considering.

**Comment by danielkza** [comment]
Ansible uses Jinja, and it's pretty common to handle security credentials when setting up systems. I just hit a case where an automatically-generated password contained a slash that was not replace by `urlencode` to generate a database URL, which is pretty unfortunate. While breaking current behavior would be problematic, why not introduce a second filter that does escape the slashes?

**Comment by ThiefMaster** [comment]
Ansible could do that. There is no need for such a change to be in Jinja itself - it is extensible enough to add custom filters or even replace builtin ones.

**Comment by danielkza** [comment]
Are any use cases that are not constructing HTML templates not considered when determining what is useful to be included in Jinja itself? For example, the Saltstack project, with similar purpose to Ansible, also uses Jinja for templating, and would benefit from the same change.

**Comment by mitsuhiko** [comment]
@danielkza what stops saltstack from providing a filter that does that?

**Comment by danielkza** [comment]
@mitsuhiko Why does Jinja include any built-in filters then? I can only guess it is because they're useful in multiple use cases. I used Ansible and Salt as two examples of where being able to escape slashes in URLs is desired, and hence, it would be valuable to have it available for everyone.

What about adding a `safe` argument to `urlencode`, as Python's `urllib.url_quote` has, so that by default slashes are preserved, but in a way that can be easily overriden?

**Comment by mitsuhiko** [comment]
Jinja attempts to provide some commonly used functionality. We have two modes for urlencoding which gets you about 95% there. You can encode entire querystrings by encoding a dict and you can encode to a common set which is valid for paths through urlencode on strings.

We don't do anything other than utf-8 or that. Because where would it stop. There are too many parts of a url, there are iris and they all have their own kinks. When we are there, why not just also provide a punycode encoder for the netloc?

**Comment by ahuffman** [comment]
I hit this issue when trying to create a file in a gitlab repository via API calls.  The gitlab api requires the slashes to be encoded.  To make this work I do:  {{ myvar | urlencode | regex_replace('/','%2F') }}.  I'm working with Ansible and Jinja2 filters in my playbook tasks.  This could be a workaround for those of you hitting this, as I validated it works.

**Comment by stootles** [comment]
I see some debate about what characters should be percent encoded, to my understanding this is currently covered in RFC3986. https://tools.ietf.org/html/rfc3986#section-2.2

Though for my use case, @ahuffman has provided a reasonable work around.

**Comment by mitsuhiko** [comment]
I want to close this because it came up again. My arguments against having this were up already in her earlier but I want to reiterate them because there is actually a PR open currently (#864) which proposes to add another filter for it to help gitlab's API.

Gitlab's API broken if placed behind all kinds of proxy setups and there are issues open for it ([Example Issue](https://gitlab.com/gitlab-org/gitlab-foss/issues/35079)). I would instead propose to document a workaround and why people should not do it.

Example workaround could be this:

```jinja
{{ value|urlencode|replace("/", "%2f") }}
```

This is a bit taking a stance but doing this can encourage people not to repeat the mistakes of others that came before them.
