### ISSUE TITLE
urlize does not check boundaries well enough if there's escaped HTML right before a URL

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/jinja#564]
```
>>> print render_template_string('{{ "test<strong>foo</strong>http://www.google.com"|escape|urlize }}')                            
<a href="http://test&lt;strong&gt;foo&lt;/strong&gt;http://www.google.com">test&lt;strong&gt;foo&lt;/strong&gt;http://www.google.com</a>
```

Does it make sense to accept anything besides a-z chars (and maybe `+` for `git+https://..` and similar URLs) at the start of a URL?

**Comment by kevin-brown** [comment]
Part of the issue here is that when we extract the URL within the text, we only extract the leading/trailing punctuation instead of extracting additional items like words. Probably because it'd be pretty complicated to actually do, and it'd break more edge cases than it fixes.

I looked around at [other urlize implementations](https://github.com/django/django/blob/6e99585c19290fb9bec502cac8210041fdb28484/django/utils/html.py#L236-L350) and they also appeared to have similar issues.

**Comment by davidism** [comment]
With the changes in #1195, this doesn't get linked at all, it just outputs the (escaped) input string. The new parser only accepts `http...` if it's at the start of the word now. I think that behavior makes sense. If you need to urlize a string that already contains HTML, you probably want to be using a more complete parser like Markdown. Any objections to closing this?
