### ISSUE TITLE
Add name and filename to Environment.from_string

### ISSUE THREAD

**Issue by harobed** [pallets/jinja#625]
What do you think about add `name` and `filename` parameters in `Environment.from_string` method ? https://github.com/pallets/jinja/blob/master/jinja2/environment.py#L849

Something like that:

```
    def from_string(self, source, name=None, filename=None, globals=None, template_class=None):
        """Load a template from a string.  This parses the source given and
        returns a :class:`Template` object.
        """
        globals = self.make_globals(globals)
        cls = template_class or self.template_class
        return cls.from_code(self, self.compile(source, name=name, filename=filename), globals, None)
```

Best regards,
Stéphane

**Comment by mitsuhiko** [comment]
What's the usecase for this? Would it not make more sense to go through a loader then? The reason is that right now there are some assumptions made about `name` (can be loaded from a loader) and `filename` (can be found on the file system).

**Comment by AlJohri** [comment]
@mitsuhiko I load templates dynamically based on some data in the context right now so I can't use the template loader. I would however like to know which template is throwing an error via a `name` parameter.

**Comment by mitsuhiko** [comment]
That does not sound like a terrific idea because it also means that this will be incredibly slow as the parser and compiler kicks in constantly which is *very* slow. If you have a pattern like this it makes more sense to make a custom loader that uses data encoded in the template name to pick up the correct template.

If you can further outline your setup I can help you find a better solution.

**Comment by AlJohri** [comment]
thanks @mitsuhiko; you're definitely right the system is a bit slow right now because there's no caching of compiled templates/bytecode. I'm working on a system where there are base templates and depending on a story `id` that's passed through the context those base templates can be overridden. So I may have a base template named `lede` that works for the generic use case, and for a specific story someone may override the `lede`. Currently I pass the template objects through the context at time of render by querying the database for templates named `lede` with the story id, falling back to the template named `lede` without any story id.

**Comment by mitsuhiko** [comment]
@AlJohri so why not do this?

```jinja
{% extends ['lede.html', 'lede-%s.html' % story.id] %}
```

**Comment by AlJohri** [comment]
@mitsuhiko oh wow, I didn't think of encoding the story id in the template name before

the template looks like this at the moment: 
<img width="331" alt="screen shot 2017-08-29 at 10 08 36 am" src="https://user-images.githubusercontent.com/2790092/29825329-1427bf7e-8ca2-11e7-8363-0e0dbc605c54.png">

would there be an easy way to wrap this to be transparent to the user ?
```jinja
{% include ['lede-' % story.id, 'lede'] %}
```

I would ideally like it to look like:
```jinja
{% myinclude 'lede' %}
```

**Comment by mitsuhiko** [comment]
I don't know what `t.lede` is but you can make that an attribute that is that list. So just do something like this:

```python
class Story(object):
    @property
    def layout_template(self):
        return ['lede-%d.html' % self.id, 'lede.html']

render_template('whatever.html', story=Story(42))
```

and then

```jinja
{% extends story.layout_template %}
{% block body %}
    ...
{% endblock %}
```

Or whatever else you feel like.

**Comment by mitsuhiko** [comment]
Also not sure why you use includes instead of extends but it works with extends and include.

**Comment by AlJohri** [comment]
Thanks for the help by the way @mitsuhiko! I really appreciate it. I've begin thinking about this issue for a while (https://github.com/pallets/jinja/issues/716).

`t.lede` is just a variable in the context that I dynamically inject: `{"t": {"lede": some_template_object}`.

Because of the nature of my problem, the names of the included templates are dynamic so I can't hardcode `lede` into the `layout_template` in the `Story` class.

Currently, before the rendering begins, I parse the ast to find all referenced templates and then inject them into `context['t']`.

I could potentially try to set `context['t']['lede']` to an array of template names like `['lede-%d.html' % self.id, 'lede.html']`. I think that might work and still be able to use the environment's template cache with a proper template loader?

**Comment by mitsuhiko** [comment]
Correct, that will work.

**Comment by AlJohri** [comment]
@mitsuhiko I'm running into another use case for this same issue. I've transitioned to using the TemplateLoader like you suggested but in my user interface, I need to be able to preview the current template before I save it. So the current template is generated dynamically using `env. from_string`. I need a name for the template because I'm trying to create a special include extension that gets templates relative to the current one. So I need `context.name` to not be `None` for my extension to work

**Comment by AlJohri** [comment]
I was able to work around the issue by passing the root template name in the context like so:

```python
current_template = context.name or context.get('root_template')
namespace, _ = split_full_template_name(current_template)
template = self.environment.get_template(f"{namespace}.{template_name}")
```

and this way I can just pass in the template name and have it assume the current template's namespace. It would be much nicer to have a `name` argument in the `Environment.from_string` method though.

**Comment by mitsuhiko** [comment]
The main reason I do not want to do this is that it introduces the idea that a template with a `name` can exist that does not have a loader. I would be willing to add a "debug name hint" or something though if that makes things easier but it will not be visible to loaders for template loading then.

**Comment by AlJohri** [comment]
@mitsuhiko that sounds good to me. I would especially love to see this name propagate to the `TemplateSyntaxError` and other exceptions. If you decide on a name I'll try to submit a PR with this feature.

**Comment by davidism** [comment]
Closing as this should be solved by using a loader. The discussed use case seems too niche to require special support in Jinja.

**Comment by guilhem-** [comment]
Hi ! Having an ansible task that populate a full tree, having control over loader does not seem direct or simple... 

#my task.yml
- name: Ensure files are populated from template dir
  template:
    src: '{{ src_dir }}'
    dest: '{{ dst_dir }}'
  with_filetree: templates/xyz

I would find usefull to be able to use directly a simple  {% __file__ %} or {% jinja.whatever %} primitive instead of trying to do things against nature such as  {{self._TemplateReference__context.name }}...

**Comment by davidism** [comment]
Take it up with Ansible to implement a loader for that functionality then.

**Comment by guilhem-** [comment]
Right.
Even if providing two times the same information to a component may sound as unoptimal from a caller point of view, I can understand other reasons exist not to do it from a callee perspective...

Finally using Ansible, it appeared to be as simple as the following code to transfer the file name information into the template....

  template:
  src: '{{ src_dir }}'
  dest: '{{ dst_dir }}'
  vars:
    file_path: "{{item.path}}"
  with_filetree: templates/xyz
