### ISSUE TITLE
Installing 2.9.1 on Python 3 < 3.6 (or 3.5) seems problematic

### ISSUE THREAD

**Issue by djc** [pallets/jinja#643]
When installing with Python 3.4, there are a bunch of errors from trying to compile code that uses new async keywords (might be due to compiling bytecode cache files in advance, which we always do in the Gentoo package manager).

```python
  File "/usr/lib64/python2.7/site-packages/jinja2/asyncfilters.py", line 7
    async def auto_to_seq(value):
            ^
SyntaxError: invalid syntax
  File "/usr/lib64/python2.7/site-packages/jinja2/asyncsupport.py", line 22
    async def concat_async(async_gen):
            ^
SyntaxError: invalid syntax
```

**Comment by ThiefMaster** [comment]
asyncsupport.py and asyncfilters.py can only be import3d on Python 3.5+ - there is simply no way around this since it uses syntax not available in older versions. The jinja2 code only imports them if `jinja2.utils.have_async_gen` is True so i guess when you want to precompile all files unconditionally you need to skip those two for older Python versions

**Comment by mitsuhiko** [comment]
What triggers this compilation?

**Comment by djc** [comment]
I think this is triggered when installing with `install.compile` set to `True` in distutils.

**Comment by mitsuhiko** [comment]
@djc are you aware of any workarounds for this?

**Comment by mitsuhiko** [comment]
BTW. There are two annoying regressions in 2.9.1 that I will fix now which will most likely mean a 2.9.2 in the next hour or so.

**Comment by mitsuhiko** [comment]
K, will take longer than an hour.

**Comment by mitsuhiko** [comment]
pip explicitly silences this in recent versions: https://github.com/pypa/pip/issues/1873

Going to just ignore this then.
