### ISSUE TITLE
Macro default arguments regression

### ISSUE THREAD

**Issue by roganov** [pallets/jinja#660]
Prior to 2.9, following code worked as expected (it rendered `1`). Since 2.9, it fails because `x` param inside the macro is undefined.
```python
import jinja2
t = jinja2.Template("""
{% set x = 1 %}
{% macro show_x(x=x) %}{{ x }}{% endmacro %}
{{ show_x() }}
""")
t.environment.undefined = jinja2.StrictUndefined
t.render()  # fails here
```

## Expected Behavior
It renders `1`

## Actual Behavior
It fails

## Full Traceback
```pytb
Traceback (most recent call last):
  File "fail.py", line 8, in <module>
    t.render()  # fails here
  File "/home/roganov/projects/jinja2.9-test/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/roganov/projects/jinja2.9-test/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roganov/projects/jinja2.9-test/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 4, in top-level template code
  File "<template>", line 3, in template
jinja2.exceptions.UndefinedError: 'x' is undefined
```

## Your Environment
* Python version: 3.5.2
* Jinja version: 2.9.4

**Comment by mitsuhiko** [comment]
You can still do the same as before but you need to give them different names:

```
{% set global_x = 1 %}
{% macro show_x(x=global_x) %}{{ x }}{% endmacro %}
{{ show_x() }}
```

This is a side effect of making clear behavior for defaults which before was very buggy. This is the same behavior now that you also have in JavaScript with defaults.

**Comment by roganov** [comment]
OK, thanks. Frankly it's not quite intuitive (i would expect templates to work as python modules), but if this behavior is intended then please close the issue.

**Comment by roganov** [comment]
> For instance what should a=b, b=a mean?
I'm not sure if I understood the question, but I think that if macro parameters and template-level variables have equal names, that template-level variables should be shadowed, just like in python.

**Comment by mitsuhiko** [comment]
@roganov you have to consider all cases. Python's default variables are in my mind a huge design mistake because they cause this behavior:

```pycon
>>> def foo(a=[]):
...  a.append(len(a))
...  return a
...
>>> foo()
[0]
>>> foo()
[0, 1]
```

Why do they do that? Because the default is resolved a function definition time and not at function declaration time. If we want to fix this we need to find a new system so I was looking around and decided to align it with JavaScript which has much saner semantics there. And in that case bindings are always referring to the same scope:

```js
let x = 1;

function showX(x=x, y=x) {
  console.log([x, y]);
}

showX();
showX(1);
```

That logs `[undefined, undefined]` and `[1, 1]` which is consistent with what Jinja2 does. If you permit a variable to both refer to the same scope binding and a higher scope you end up with loads of scoping issues.
