### ISSUE TITLE
Allow multiple attributes in `sort` filter

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/jinja#670]
`foo|sort(attribute='name,id')` is quite useful in some cases.

The current workaround (using the fact that sorting is stable) looks extreme awful and is not intuitive: `foo|sort(attribute='id')|sort(attribute='name')`

**Comment by davidism** [comment]
Would it be useful to support something like `name,-id` to mean "name ascending, id descending"? Otherwise you'd still have to chain sorts if the directions were different.

**Comment by ThiefMaster** [comment]
Does that happen very often? There's no clean way to implement such modifiers since it's a generic function handling the attribute lookup from a string (remember, you can do stuff like `attribute='1.name'` which is useful when dealing with dict items for example) - and that function is not only used for sorting.

**Comment by voussoir** [comment]
Hi, sorry for the necro and wall of text but this is something I would be interested in writing a PR for.

Subsorting is usually done with tuples:

```Python
>>> dicts = [
...     {'name': 'Mike', 'age': 20},
...     {'name': 'Angela', 'age': 20},
...     {'name': 'Alice', 'age': 30},
... ]
>>>
>>> sorted(dicts, key=lambda d: (d['age'], d['name']))
[{'name': 'Angela', 'age': 20}, {'name': 'Mike', 'age': 20}, {'name': 'Alice', 'age': 30}]
>>>
>>> sorted(dicts, key=lambda d: (d['name'], d['age']))
[{'name': 'Alice', 'age': 30}, {'name': 'Angela', 'age': 20}, {'name': 'Mike', 'age': 20}]
```

And jinja evals tuples just fine:

```Python
>>> import jinja2
>>> jinja2.Template('{{ a|sort(attribute=("test",)) }}').render(a=[])
make_attrgetter recieved: ('test',)
'[]'
```

This is good because you don't have to let commas have a special meaning as in the OP.

`make_attrgetter` already has rules on [how to prepare its input into a "parts" list](https://github.com/pallets/jinja/blob/3d7cfc844bfc826a325573f550681121051004ea/jinja2/filters.py#L68-L73). It could have a new rule for tuples that recursively prepares the elements:

```Python
def prepare(attribute):
    if attribute is None:
        attribute = []
    elif isinstance(attribute, tuple):
        attribute = tuple(prepare(part) for part in attribute)
    elif isinstance(attribute, string_types):
        attribute = [int(x) if x.isdigit() else x for x in attribute.split('.')]
    else:
        attribute = [attribute]
    return attribute

attribute = prepare(attribute)
```

If `attrgetter` detects that a part is a tuple, it can also use recursion to `getitem` each piece separately. The final results will therefore also be a tuple, so we can return `results[0]` when there is only 1 item to keep it backwards compatible. You will only receive a tuple out if you put a tuple in.

&nbsp;

Python itself does not have an answer to the "one column asc, other column desc" [question](https://stackoverflow.com/a/16537717) other than negating integers, so if that doesn't make it into Jinja this would still be a net gain.

Thoughts?

**Comment by ryanmerolle** [comment]
Would it be possible to also extend this to allow sorting based on an attribute and a filter?

**Comment by mayuropensource** [comment]
Talked to @davidism and implemented the initial proposal.
