### ISSUE TITLE
Can we get an {% empty %} tag?

### ISSUE THREAD

**Issue by priestc** [pallets/jinja#77]
Django has this really cool tag called {% empty %}, which lets you do this:

```
{% for item in list %}
    <tr><td>{{ item }}</td></tr>
{% empty %}
    <tr><td>Nothing to show!</td></tr>
{% endfor %}
```

which is short for

```
{% if list %}
    {% for item in list %}
        <tr><td>{{ item }}</td?</tr>
    {% endfor %}
{% else %}
    <tr><td>Nothing to show!</td></tr>
{% endif %}
```

Since switching to jinja, I have really missed this tag :(

**Comment by WloHu** [comment]
If `list` in code is a generator and `for` and `if` blocks work in the same way as in Python then the `if-for` construct doesn't solve the problem because generators are always truthy, plus such construct is less idiomatic than `empty` block.

I don't know if you can add a flag to check if loop has run, check for `NameError: name 'item' is not defined` or add helper variable to `list(generator)` at Jinja level. If not, then the only solutions is to add the `empty` block or convince Python devs that empty generators should be falsy (to avoid ugly checking by handling `StopIteration` and "pushing back" popped item).

**Comment by mitsuhiko** [comment]
The `else` block in Jinja works like the `empty` block in Django already. No change is necessary here.
