### ISSUE TITLE
Segfaulting in big template?

### ISSUE THREAD

**Issue by ctheune** [pallets/jinja#784]
This might be similar/related to #372 and #556 but it could also be quite different.

---

## Expected Behavior
Render a very large template might cause Python to use a log of RAM and maybe give a MemoryError if we exceed memory.

## Actual Behavior

Rendering a very large (~7MiB) template file with simple {{...}} replacements causes Python to segfault after spending a lot of CPU time.

## Template Code
```jinja
<<7mib of a single simple substituion repeated 100ks of lines>>

```

## Full Traceback
```pytb

[   85.212279] python[1220]: segfault at 7ffe8eb93ff8 ip 00007fbf89c507b3 sp 00007ffe8eb93fa0 error 6 in libpython2.7.so.1.0[7fbf89b40000+1ba000]

```

## Your Environment
* Python version:  2.7.11
* Jinja version: 2.9.6

**Comment by snordhausen** [comment]
I was able to reproduce the segfault with the following code:
```
from jinja2 import Environment

RANGE = 27000
data = {i: 2*i for i in range(RANGE)}
template_string = "".join('{{ data.%s }} ' % i for i in range(RANGE))
print("length of template string: %s" % len(template_string))

environment = Environment()
template = environment.from_string(template_string)
rendered = template.render(data=data)

print("length of rendered string: %s" % len(rendered))
```
This template has a length of only ~450kB and still segfaults. After lowering `RANGE` to 26,000, the code works.
Note that this is NOT an out of memory error. Via `dmesg`, I can see that the kernel did not report an OOM situation, it reported `python[9163]: segfault at 7ffe8c282ff8.....`.

Environment for me is Python 3.6.3 on Ubuntu 17.04 64bit with Jinja version 2.10.0.

**Comment by snordhausen** [comment]
Further investigation shows that this is a bug in CPython, not a bug in Jinja.

The code I provided above works fine (and produces the expected result) when I run it with Pypy instead of CPython. After noticing that, I found that the segfault is triggered by [this line](https://github.com/pallets/jinja/blob/master/jinja2/environment.py#L551) in Jinja. So it is Python's builtin `compile` function that segfaults.

After noticing that, I was able to reproduce the segfault with this code:
```
args = "42 if True else 43," * 270000
code = "(%s)" % args
compile(code, "foobar", "exec")
```
This produces a simplified version of the code that was auto-generated for my previous example. I can reproduce the segfault with Python version 2.7.13, version 3.6.3 and also the current git master of CPython. I'll open a ticket in CPython's bugtracker.

**Comment by davidism** [comment]
Thanks for  looking into this @snordhausen.

**Comment by snordhausen** [comment]
This issue will be gone in Python 3.7 because https://github.com/python/cpython/pull/3015 got merged. Since [the original bug report](https://bugs.python.org/issue31113) is already closed, it seems like there will be no backport to Python 3.6 or 2.7.
