### ISSUE TITLE
Weird tracebacks if call macro as function from template.module

### ISSUE THREAD

**Issue by zubchick** [pallets/jinja#805]
## Expected Behavior
Normal jinja traceback with correct linenos and source hints

## Actual Behavior
Weird tracebacks with wrong linenos and source hints

## Source Code
**test.template**
```jinja
{% macro test() %}{{ 1/0 }}{% endmacro %}
```
**test.py**
```python
from jinja2 import Environment, FileSystemLoader

env = Environment(loader=FileSystemLoader('.'))
t = env.get_template('test.template')
t.module.test()
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "test_jinja.py", line 5, in <module>
    t.module.test()
  File "/Users/zubchick/.virtualenvs/vins-dm/lib/python2.7/site-packages/jinja2/runtime.py", line 575, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/zubchick/.virtualenvs/vins-dm/lib/python2.7/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "./test.template", line 15, in macro

ZeroDivisionError: division by zero
```

## Your Environment
* Python version: Python 2.7.13
* Jinja version: 2.10

**Comment by zubchick** [comment]
anyone?

**Comment by davidism** [comment]
This isn't possible to fix. When rendering a template, the execution is wrapped in a helper that rewrites the line numbers in tracebacks. You're executing the code directly from the compiled module, so you see the compiled line number, not the mapping to the original source. It shows an empty code line because there's no line 15 in the source file.
