### ISSUE TITLE
Template.py file is not present under jinja2 repository

### ISSUE THREAD

**Issue by pravin123456** [pallets/jinja#809]
The issue tracker is a tool to address bugs in Jinja itself.
Please use the #pocoo IRC channel on freenode or Stack Overflow for general
questions about using Jinja or issues not related to Jinja.

If you'd like to report a bug in Jinja, fill out the template below and provide
any extra information that may be useful / related to your problem.
Ideally, you create an [MCVE](http://stackoverflow.com/help/mcve) reproducing
the problem before opening an issue to ensure it's not caused by something in
your code.

---

## Expected Behavior
Tell us what should happen

## Actual Behavior
Tell us what happens instead

## Template Code
```jinja
Paste the template code (ideally a minimal example) that causes the issue

```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version:
* Jinja version:2.x

**Comment by ThiefMaster** [comment]
What is your actual issue?

**Comment by pravin123456** [comment]
Template.py file is not present under jinja2 package.

[root@emp]# cp ../jinja2/jinja2/* .
[root@emp]# ls
asyncfilters.py  bccache.py  compiler.py   debug.py     environment.py  ext.py      _identifier.py  __init__.py  loaders.py  nativetypes.py  optimizer.py  runtime.py  tests.py  visitor.py
asyncsupport.py  _compat.py  constants.py  defaults.py  exceptions.py   filters.py  idtracking.py   lexer.py     meta.py     nodes.py        parser.py     sandbox.py  utils.py

And getting below error-
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 40, in <module>
    import ansible.constants as C
  File "/usr/local/lib/python3.5/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
ImportError: cannot import name 'Template'
Can you pl help me with above issue?

**Comment by ThiefMaster** [comment]
I have no idea what you are trying to do there (you should not have to copy around files from Jinja manually). If Ansible is broken, ask the ansible developers.

Also, you are misreading the error. There is no template.py in Jinja, the `Template` class is imported in `__init__.py` which is why you can do `from jinja2 import Template`, but something is broken in your environment (maybe a custom jinja2.py in your PYTHONPATH?).

Anyway, not a Jinja issue, the packages work fine, if you mess around with files manually like in your example you will run into problems. Python has a package manager for a reason (and so do linux distributions, if you install ansible using your distro's package manager it will automatically install the correct Jinja version in the correct place).

**Comment by pravin123456** [comment]
Okay, but i had downloaded the jinja2 from github also installed rpm for ansible using:
pm -ivh https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/a/ansible-2.4.2.0-1.el7.noarch.rpm

on Rhel7.

git clone http://github.com/mitsuhiko/jinja2.git

Still not able to run the playbook due to Template module dependancy.

Can you pl guide me with the exact workaround soln or steps to avoid this problem for rhel7.4 version?

Thanks,
-Pravin.

**Comment by ThiefMaster** [comment]
You do not need to git clone this repo. You need to install ansible properly.

Why are you even trying to install Ansible from a Fedora repo if you are on RHEL? Also, don't install random RPMs manually, use `yum` instead. See http://docs.ansible.com/ansible/latest/intro_installation.html#latest-release-via-yum which is what you can find *very* easily if you just google on how to install ansible...

In any case, this is not the right place for this. Please ask in a place related to Ansible or Fedora if you still can't solve this.
