### ISSUE TITLE
jinja2.DebugUndefined behavior not expected

### ISSUE THREAD

**Issue by tblanarik** [pallets/jinja#811]
## Expected Behavior
When asking for the property of an Undefined variable and using jinja2.DebugUndefined as the "undefined" behavior of my Environment, I expected the tag to be returned as it originally was in the Template - just like when you have an Undefined variable in your Template normally.

```
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ VAR }}").render({"VAR": "Hello"}) # Should return Hello
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ NOVAR }}").render({"VAR": "Hello"}) # Should return {{ NOVAR }}
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ NOVAR.items }}").render({"VAR": "Hello"}) # Should return {{ NOVAR.items }}
```

## Actual Behavior
Throws an UndefinedError

```
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ VAR }}").render({"VAR": "Hello"}) # Correctly returns Hello
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ NOVAR }}").render({"VAR": "Hello"}) # Correctly returns {{ NOVAR }}
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ NOVAR.items }}").render({"VAR": "Hello"}) **# Throws an UndefinedError: 'NOVAR' is undefined**
```

## Template Code
```jinja
jinja2.Environment(undefined=jinja2.DebugUndefined).from_string("{{ NOVAR.items }}").render({"VAR": "Hello"})
```

## Full Traceback
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "conda\conda\envs\Py27Env\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "conda\conda\envs\Py27Env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "conda\conda\envs\Py27Env\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'NOVAR' is undefined
```

## Your Environment
* Python version: Python 2.7.13
* Jinja version: 2.10

**Comment by tblanarik** [comment]
Taken from the [Template Designer](http://jinja.pocoo.org/docs/2.10/templates/#defined) docs:

> Implementation
> For the sake of convenience, foo.bar in Jinja2 does the following things on the Python layer:
> 
> check for an attribute called bar on foo (getattr(foo, 'bar'))
> if there is not, check for an item 'bar' in foo (foo.__getitem__('bar'))
> if there is not, return an undefined object.

I think I was imagining a step before these 3, which is:
> Check that foo even exists. If not, return an undefined object.

**Comment by EtiennePelletier** [comment]
Hi @tblanarik ,
It is by design that objects from the Undefined class (as well as StrictUndefined and DebugUndefined) raise an UndefinedError when trying to use \_\_getitem\_\_ or \_\_getattr\_\_.
Therefore, the following example (simplified from the 3rd line in your first post) starts by evaluating NOVAR, which returns an Undefined object. Then, undefined.\_\_getitem\_\_('items') throws the UndefinedError.
```python
jinja2.Template("{{ NOVAR.items }}", undefined=jinja2.DebugUndefined).render()
```

You're right when you say that `NOVAR.items` is undefined, but it is undefined because `NOVAR` is undefined.
**The next version of jinja2 (2.11) will include a new `ChainableUndefined` class that allows getitem and getattr.** If there's a chain with multiple values using getitem and getattr, the Undefined will take the name of the first element in the chain that is undefined.
https://github.com/pallets/jinja/blob/master/CHANGES.rst

Sample usage:
```python
>>> import jinja2
>>> jinja2.Template("{{ foo.bar['baz'] | default('val') }}", undefined=jinja2.ChainableUndefined).render()
'val'
>>>
>>> # The following is not recommended because it would break when
>>> # provided defined values but it illustrates the principle of undefined
>>> # keeping the name of the first undefined element in the chain.
>>> jinja2.Template("{{ foo.bar['baz']._undefined_name }}", undefined=jinja2.ChainableUndefined).render()
'foo'
>>> jinja2.Template("{{ foo.bar['baz']._undefined_name }}", undefined=jinja2.ChainableUndefined).render(foo=2)
'bar'
```

If you're attached to the debug functionality and want to use it along with the ChainableUndefined, here's one thing you'll be able to do:
```python
>>> class DebugChainableUndefined(jinja2.ChainableUndefined, jinja2.DebugUndefined):
...     pass
... 
>>> jinja2.Template("{{ foo.bar['baz'] }}", undefined=DebugChainableUndefined).render()
'{{ foo }}'
```
