### ISSUE TITLE
Truncate changed behavior: warn users

### ISSUE THREAD

**Issue by danielmotaleite** [pallets/jinja#818]
as per issue https://github.com/ansible/ansible/issues/36599 , truncate changed behavior, that by itself is bad, but the documentation is both outdated and warns users in a way that can be easily ignored

outdated because of this:
```
 truncate(s, length=255, killwords=False, end='...', leeway=None)
```
Please update the `leeway=None` to `leeway=5`, as it is now the new default

the warning, it is in the end, after the example, and that can be easily ignored. Please move it to the top or before the example and probably add in bold `change in behavior since version X:` , so users may see more clearly what changed

**Comment by danielmotaleite** [comment]
i forgot where i'm checking the documentation: http://jinja.pocoo.org/docs/2.10/templates/#list-of-builtin-filters

**Comment by ricky-undeadcoders** [comment]
I don't agree that the documentation needs updating.  The truncate function actually does default leeway=None, but then overrides it using env.policies to be 5.  However, this is clearly documented here http://jinja.pocoo.org/docs/2.10/templates/#list-of-builtin-filters with the following statement:

"The default leeway on newer Jinja2 versions is 5 and was 0 before but can be reconfigured globally."

I'm not a maintainer, but I wouldn't support falsely stating that leeway defaults to 5 when it actually defaults to None, and then is overridden to be 5; especially since this is already explicitly stated in the documentation that default leeway is 5.

From the code (version 2.10):
```
def do_truncate(env, s, length=255, killwords=False, end='...', leeway=None):
    if leeway is None:
        leeway = env.policies['truncate.leeway']
```
