### ISSUE TITLE
Missing version added in docs for equalto after adding eq

### ISSUE THREAD

**Issue by sivel** [pallets/jinja#850]
## Expected Behavior
`equalto` was added in 2.8, this is now missing from the documentation.

## Actual Behavior
The documentation has lost the version added context after making `equalto` an alias and adding `eq`

## Template Code

```jinja
N/A

```

## Full Traceback

```pytb
N/A

```

## Your Environment
* Python version: N/A
* Jinja version: N/A

**Comment by davidism** [comment]
This is due to some Sphinx processing that Click adds to its docs. It's picking up the wrong alias / docs for the main name, so it doesn't render the docstring. That's where to start looking.

**Comment by sivel** [comment]
It appears the actual issue is related to dropping `test_equalto` and adding operator tests in https://github.com/pallets/jinja/commit/d62f0500a70aaab5762691d4feb6b9bb2724a1ba. This results in no longer having a docstring for the method being used in the test, and thus no `.. versionadded:: 2.8` spec.

I'm not sure how we want to approach this.  Maybe a wrapper/closure that adds a docstring?

**Comment by sivel** [comment]
The overhead of addressing this is not worth solving.

Thanks for the response, I'll go ahead and close.

**Comment by davidism** [comment]
I think what I should have done is added some `versionchanged` directives to that section in the page. Would that be enough for your use case?

**Comment by sivel** [comment]
@davidism I think it probably makes sense to just handle that in the sphinx template.  I think any change could be helpful for historical context of these features.

**Comment by davidism** [comment]
Going to flip on this again, sorry! There's just no nice way that I can see to add this. Since the docs for the tests are autogenerated by a Sphinx directive, there's no way to insert something in the middle. Placing the versionchanged at the bottom of the section moves it away from what someone would actually be looking at, and makes it look like it's about the last test (`upper`).

Given that relatively few users are using <2.10 now, I think it's ok to assume people have this now.
