### ISSUE TITLE
jinja2 incompatibility with paths created using pathlib

### ISSUE THREAD

**Issue by breisfeld** [pallets/jinja#870]
As part of refactoring, I have been converting my application from using `os.path` to `pathlib`.

However, it appears that `jinja2` is incompatible with paths created using `pathlib.Path`.

For example, if `tdir` is a `pathlib` Path object, the following generates an error:

`jinja_environment = Environment(loader=FileSystemLoader(tdir), trim_blocks=False, lstrip_blocks=True)`,

where the bottom of the error traceback is 

```
    jinja_environment = Environment(loader=FileSystemLoader(tdir),
  File ".../python/anaconda3/lib/python3.6/site-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```

If I convert `tdir` to a string, things work fine.

jinja: v 2.10
python: v3.6.5

**Comment by ThiefMaster** [comment]
Are python libraries supposed to accept pathlib Path objects in places where usually a string path is provided? If yes, a pull request (that does not break Python 2 compatibility!) would be appreciated.

**Comment by breisfeld** [comment]
I don't know about 'supposed to', but pathlib seems to be picking up steam as an alternative to os.path. I will take a look to see if this change could be made without affecting Python 2 compatibility.

**Comment by davidism** [comment]
PRs for this: #871, #874, #876. Please push new commits rather than new PRs for every review.

However, I don't think we should be converting anything to string. We don't do anything with the paths that requires them to be a string. Python functions already know how to use `Path` and we're just passing on to them.

The original issue was that `Path` is not `string_types`, so the loader was incorrectly calling `str` on it. The solution should be to fix the `isinstance` check to check that it's not an iterable.

**Comment by dedekind** [comment]
Experienced the following crash today.

{% include path %}

where "path" is a pathlib.Path object, not a string. Rendering the template crashes:

TypeError: 'PosixPath' object is not iterable

Does this belong to this ticket?

**Comment by ngfgrant** [comment]
This issue also arises if a project uses pytest `tmpdir` for testing.

**Comment by iomintz** [comment]
@dedekind, I believe that is also due to FileSystemLoader not supporting pathlib.Paths. It does belong here.
