### ISSUE TITLE
Any appetite to be able to pass a macro for the map() filter?

### ISSUE THREAD

**Issue by seaders** [pallets/jinja#910]
I've basically done this in my code,

template:

    {% macro event_detail(event) -%}
        {{ event.name }}<br />{{ event.startdt }}
    {%- endmacro %}

    {{ events|custom_map(macro=event_detail)|join(', ') }}

code:

    @app.template_filter()
    def extra_map(l, macro):
        return map(macro, l)

It's a pretty simple premise, but works really nice, and makes map much more powerful and flexible.  If there's any interest, I'll do it up proper in `prepare_map` in `filters.py` and PR it.

**Comment by flexferrum** [comment]
Had the same request in C++ implementation: https://github.com/flexferrum/Jinja2Cpp/issues/50

Implemented it as a dedicated `applymacro(value, name, *args, **kwargs)` filter which can be called from `map` like this: `{{ events|map('applymacro' name='event_detail')|join(', ') }}`

**Comment by davidism** [comment]
@seaders seems reasonable.

As with a lot of things in Jinja, I don't know if there's a design reason the `map` filter doesn't already handle callables. Maybe @mitsuhiko can comment.

Quick look at `jinja2.filters.do_map()`, uses `context.environment.call_filter()`. Might be able to detect if the first argument is a callable instead of a string, and use `context.call()` to invoke it.

@flexferrum is there a particular reason you went with a new filter instead of extending the map filter?

**Comment by flexferrum** [comment]
@davidism, I see at least two such reason:

1. You can apply macro as a filter for the single arbitrary value (not only for list/tuple)
2. You can keep the current sementic of the `map` filter which can apply only filters, but not any callable.

**Comment by davidism** [comment]
See https://github.com/pallets/jinja/pull/911#issuecomment-549436594 for why I've decided to close this.
