### ISSUE TITLE
Release a version containing #867

### ISSUE THREAD

**Issue by flying-sheep** [pallets/jinja#973]
Hi! In #867, you fixed some `DeprecationWarning`s that were swamping people’s pytest output.

Unfortunately they still do, since you didn’t put the commit into 2.10.1. Could you please release a version with that fix?

**Comment by davidism** [comment]
Closing as this issue won't affect our release schedule. Thank you for the interest.

**Comment by flying-sheep** [comment]
What is your release schedule?

**Comment by dhimmel** [comment]
Also interested in a release that includes #867, since `jinja2` is the only package we use that [causes warnings](https://travis-ci.com/manubot/manubot/jobs/205309499#L541) in Python 3.7. Simplifying the Python output logs are important for our use case, so these warnings are keeping us using Python 3.6.

**Comment by jbarreneche** [comment]
Hi @davidism ! What's the schedule for a new release that contains that simple fix? (neither of the links you provided help answering that)
The fix has been in master for quite a while and hasn't been backported to 2.10 branch. I understand it's not something critical but it's a very annoying warning for projects using new versions of python. I can back port it to the branch 2.10 branch if that helps.

Thanks!

**Comment by ThiefMaster** [comment]
@jbarreneche a PR (with the fix and a changelog entry) for 2.10 would be welcome and indeed help speed it up!
